export const ADD_COMMENT = 'ADD_COMMENT'
export const ADD_COMMENTS = 'ADD_COMMENTS'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const EDIT_COMMENT = 'EDIT_COMMENT'
export const QUERY_COMMENTS = 'QUERY_COMMENTS'
export const UPVOTE_COMMENT = 'UPVOTE_COMMENT'
export const DOWNVOTE_COMMENT = 'DOWNVOTE_COMMENT'

